[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "pillow>=11.3.0",
    "python-telegram-bot==20.8",
    "pytz>=2025.2",

]
